### PR TITLE
Switch maintainers to frjo and deekayen.

### PR DESCRIPTION
**Pull request by deekayen**
@chrisherberte hasn't responded at all to PR #2.

### CODE REVIEW

**Comment by herbdool** [comment]
Hi @klonos @jenlampton,

@frjo and @deekayen have followed the steps outlined for abandoned projects https://github.com/backdrop-ops/contrib It says that a Backdrop Contrib Admin needs to create a PR to add the new maintainer to the README.

**Comment by jenlampton** [comment]
Hi @frjo and @deekayen !

Thank you so much for following the application process to get maintainership of this module :)  

Since I want to be respectful of @chrisherberte's time and efforts here, I'd be more comfortable adding you two as co-maintainers for this project now, and we can remove @chrisherberte if he chimes in and agrees to be removed (or if an exorbitant amount of time passes).

Can you please update the PR so that it does not remove @chrisherberte at this time?

**Comment by deekayen** [comment]
@jenlampton PR #3 updated.

**Comment by jenlampton** [comment]
Fantastic, thank you @deekayen!  I have merged your PR and you now have free license to do as you wish to the module.  

I expect that @chrisherberte won't mind being removed as a maintainer, but I want to give him a little more time to respond. I just didn't want to hold up your maintainership to wait for that response.

**Pull request merged**
